## 1: Weekly Temperature Tracker - 10 points
You recorded daily temperatures for a week: [22, 24, 19, 23, 25, 21, 20]. Find the average, the hottest day's temperature, the coldest day's temperature, and how many days were above 22.

In [1]:
import numpy as np

In [10]:
temp = np.array([22, 24, 19, 23, 25, 21, 20])
temp

array([22, 24, 19, 23, 25, 21, 20])

In [3]:
temp.mean()

np.float64(22.0)

In [5]:
temp.max()

np.int64(25)

In [6]:
temp.min()

np.int64(19)

In [34]:
temp = np.array([22, 24, 19, 23, 25, 21, 20])
np.sum(temp > 22)

np.int64(3)

## 2: Monthly Sales Report - 10 points
A store's sales for 4 weeks across 3 products are stored in this 2D array (rows = weeks, columns = products):.

sales = np.array([[120, 340, 210],
                   [150, 300, 250],
                   [170, 360, 230],
                   [140, 320, 260]])
Find the total sales per product and the total sales per week

In [26]:
sales = np.array([[120, 340, 210], [150, 300, 250], [170, 360, 230], [140, 320, 260]])

print('Total sales per product')
product1 = sales[ : , 0]
total = sum(product1)
total
print(f' Product 1 total sales: {total}')

product2 = sales[ : , 1]
total = sum(product2)
total
print(f' Product 2 total sales: {total}')

product3 = sales[ : , 2]
total = sum(product3)
total
print(f' Product 3 total sales: {total}')

print('-' * 30)

print('Total sales per week')

week1 = sales[0, : ]
total = sum(week1)
print(f' Week 1 total sales: {total}')

week2 = sales[1, : ]
total = sum(week2)
print(f' Week 2 total sales: {total}')

week3 = sales[2, : ]
total = sum(week3)
print(f' Week 3 total sales: {total}')

week4 = sales[3, : ]
total = sum(week4)
print(f' Week 4 total sales: {total}')

Total sales per product
 Product 1 total sales: 580
 Product 2 total sales: 1320
 Product 3 total sales: 950
------------------------------
Total sales per week
 Week 1 total sales: 670
 Week 2 total sales: 700
 Week 3 total sales: 760
 Week 4 total sales: 720


## 3: Unique Customer Visits - 10 points
A restaurant logs customer IDs each time someone visits during a week: [102, 105, 102, 110, 108, 105, 102, 110, 115]. Find the list of unique customers, and how many total unique customers visited.


In [27]:
customer_id = np.array([102, 105, 102, 110, 108, 105, 102, 110, 115])
customer_id

array([102, 105, 102, 110, 108, 105, 102, 110, 115])

In [36]:
unique_customers = np.unique(customer_id)

In [40]:
np.size(unique_customers)

5

## 4: Exam Score Ranking - 10 points
An array holds exam scores for 10 students: [67, 88, 45, 92, 76, 59, 64, 30, 71, 51]. Sort the scores from lowest to highest, and find the index (position) of the student with the highest score in the original array.


In [30]:
scores = [67, 88, 45, 92, 76, 59, 64, 30, 71, 51]

arr_scores = np.array(scores)

arr_scores


array([67, 88, 45, 92, 76, 59, 64, 30, 71, 51])

In [31]:
np.sort(arr_scores)

array([30, 45, 51, 59, 64, 67, 71, 76, 88, 92])

In [32]:
np.argmax(arr_scores)

np.int64(3)

## 5: Employee Bonus Filter - 10 points
An array holds employee performance scores out of 100: [45, 78, 92, 60, 88, 33, 95, 70]. To give a 20k bonus to employees who scored above 80, flag them as 1 and 0 otherwise. Also print how many employees qualify.

In [19]:
score = np.array([45, 78, 92, 60, 88, 33, 95, 70])
score

array([45, 78, 92, 60, 88, 33, 95, 70])

In [23]:
qualified = np.where(score > 80, 1, 0)
qualified

array([0, 0, 1, 0, 1, 0, 1, 0])

In [24]:
np.sum(qualified)

np.int64(3)